image: python:3.13-bullseye

before_script:
  - pip install -r requirements.txt

pages:
  stage: deploy
  tags:
  - lin6
  - docker
  script:
  - mkdocs build --strict --verbose
  artifacts:
    paths:
    - public
